services:
  backend:
    build:
      context: .
      dockerfile: RecipesBackend/Dockerfile
    ports:
      - 8080:80
    depends_on:
      - db
    develop:
      watch:
        - action: rebuild
    environment:
      - "ConnectionStrings__Mongo=mongodb://db:27017"
  
  db:
    image: mongodb/mongodb-community-server:6.0-ubi8
    ports:
      - 27018:27017
    expose:
      - 27017
    volumes:
      - type: bind
        source: ./data
        target: /data/db